name: Report a Bug
description: Found a bug? Let us know!
labels: 'bug'
body:
# bug description
- type: textarea
  id: descrption
  attributes:
    label: Describe The Bug
    description: "A clear and concise description of what the bug is."
  validations:
    required: true
# steps to reproduce
- type: textarea
  id: steps
  attributes:
    label: Steps To Reproduce
    description: "Steps to reproduce the behavior."
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: false
# expected behavior
- type: textarea
  id: expected
  attributes:
    label: Expected Behavior
    description: "A clear and concise description of what you expected to happen."
  validations:
    required: false
# screenshots
- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: "If applicable, add screenshots to help explain your problem."
  validations:
    required: false
# desktop
- type: textarea
  id: desktop
  attributes:
    label: Desktop
    description: "Please complete the following information."
    placeholder: |
      - OS: [e.g. iOS]
      - Browser [e.g. chrome, safari]
      - Version [e.g. 22]
  validations:
    required: false
# smartphone
- type: textarea
  id: mobile
  attributes:
    label: Smartphone
    description: "Please complete the following information."
    placeholder: |
      - Device: [e.g. iPhone6]
      - OS: [e.g. iOS8.1]
      - Browser [e.g. stock browser, safari]
      - Version [e.g. 22]
  validations:
    required: false
# additional context
- type: textarea
  id: additional-context
  attributes:
    label: Additional Context
    description: "Add any other context about the problem here."
  validations:
    required: false
